# Nome do banco de dados na memória (restaurantdb)
spring.datasource.url=jdbc:h2:mem:restaurantdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Habilita o Console Web do H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
spring.h2.console.settings.web-allow-others=true

# Hibernate/JPA Configurations
# "update" cria as tabelas automaticamente com base nas classes @Entity
spring.jpa.hibernate.ddl-auto=update
# Exibe no console as queries SQL executadas pelo Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true